# Generated by Django 4.2.3 on 2023-08-28 08:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_alter_user_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reaction',
            field=models.ManyToManyField(blank=True, related_name='post_reacted', to=settings.AUTH_USER_MODEL),
        ),
    ]
