# Generated by Django 4.2.3 on 2023-08-28 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_post_reaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='reaction',
            new_name='reactions',
        ),
    ]
