# Generated by Django 4.2.3 on 2023-08-06 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_category_comment_bid_auction_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='categories',
        ),
        migrations.AddField(
            model_name='auction',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='autions', to='auctions.category'),
        ),
        migrations.AddField(
            model_name='auction',
            name='image_url',
            field=models.CharField(default=None, max_length=2000),
            preserve_default=False,
        ),
    ]
