# Generated by Django 4.2.3 on 2023-08-07 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='auction',
            new_name='auctions',
        ),
    ]
