# Generated by Django 4.2.3 on 2023-08-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_auction_id_alter_bid_id_alter_category_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='status',
            field=models.CharField(default='active', max_length=32),
        ),
    ]
