# Generated by Django 4.2.3 on 2023-08-09 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_comment_parent_comment_comment_sibling_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to='auctions.category'),
        ),
    ]
